# -*- coding: utf-8 -*-
"""1-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EyBSGKFLjGodipFe0Usj4adDfZgyhgG4
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
#個別のデータの詳細
def gurunavi(url):
    details={}
    r = requests.get(url)
    soup = BeautifulSoup(r.content, 'html.parser')
    #店名
    shop=soup.find('table',attrs={'class':'basic-table'})
    shop=shop.find('p',attrs={'class':'fn org summary'}).text.replace('\xa0','')
    details['店舗名']=shop
    #電話番号
    tel=soup.find('table',attrs={'class':'basic-table'}).find('tr',attrs={'id':'info-phone'}).find('td').find('ul').find('li').find('span',attrs={'class':'number'}).text
    details['電話番号']=tel
    #住所　市区町村
    address1=soup.find('span',attrs={'class':'region'}).text
    address2=soup.find('span',attrs={'class':'locality'}).text
    import re
    def divide_address(address):
        matches = re.match(r'(...??[都道府県])((?:旭川|伊達|石狩|盛岡|奥州|田村|南相馬|那須塩原|東村山|武蔵村山|羽村|十日町|上越|富山|野々市|大町|蒲郡|四日市|姫路|大和郡山|廿日市|下松|岩国|田川|大村)市|.+?郡(?:玉村|大町|.+?)[町村]|.+?市.+?区|.+?[市区町村])(.+)' , address)
        address=[matches[1],matches[2],matches[3]]
        return address
    details['都道府県']=divide_address(address1)[0]
    details['市区町村']=divide_address(address1)[1]
    details['番地']=divide_address(address1)[2]
    details['建物名']=address2
    #URL
    web=soup.find('link')
    details['webサイト']=web.get('href')
    #SSL
    def ssl(u):
        if u.startswith('https://')==True:
            return True
        else:
            return False
    ss=ssl(web.get('href'))
    details["SSL証明書"]=ss
    return details
#データの入力
df01=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/1mhxs8wy0000/?sc_lid=r-r_history01'),index=[1])
df02=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/n9dm4dmj0000/?sc_type=area&sc_area=AREAL3102&sc_dsp=rs_141215'),index=[2])
df03=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/naf9zswm0000/?sc_type=area&sc_area=jp&sc_dsp=rs_137302'),index=[3])
df04=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/444gbcer0000/?sc_type=area&sc_area=jp&sc_dsp=rs_139817'),index=[4])
df05=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/naf9zswm0000/?sc_type=area&sc_area=jp&sc_dsp=rs_137302'),index=[5])
df06=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/kdbd8tvy0000/?sc_type=area&sc_area=jp&sc_dsp=rs_140072'),index=[6])
df07=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/pbdab5sf0000/?sc_type=area&sc_area=jp&sc_dsp=rs_139162'),index=[7])
df08=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/naf9zswm0000/?sc_type=area&sc_area=jp&sc_dsp=rs_137344'),index=[8])

df09=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/ga2e400/?sc_type=area&sc_area=jp&sc_dsp=rs_138208'),index=[9])
df10=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/8h5w546g0000/?sc_type=area&sc_area=jp&sc_dsp=rs_140064'),index=[10])
df11=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/597mz0tg0000/?sc_type=area&sc_area=jp&sc_dsp=rs_138675'),index=[11])
df12=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/a147204/?sc_type=area&sc_area=jp&sc_dsp=rs_136156'),index=[12])
df13=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/kabr700/?sc_type=area&sc_area=AREAL3102&sc_dsp=rs_141377'),index=[13])
df14=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/n238910/?sc_type=area&sc_area=jp&sc_dsp=rs_142352'),index=[14])
df15=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/k065440/?sc_type=area&sc_area=AREAL3102&sc_dsp=rs_140906'),index=[15])
df16=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/f4nnus340000/?sc_type=area&sc_area=jp&sc_dsp=rs_140055'),index=[16])
df17=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/dpgbke1j0000/?sc_type=area&sc_area=AREAL3102&sc_dsp=rs_142234'),index=[17])
df18=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/g0kf3ubt0000/?sc_type=area&sc_area=jp&sc_dsp=rs_138351'),index=[18])
df19=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/max2hsdn0000/?sc_type=area&sc_area=AREAL3102&sc_dsp=rs_141068'),index=[19])
df20=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/h204601/?sc_type=area&sc_area=PREF01&sc_dsp=rs_140700'),index=[20])
df21=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/k137335/?sc_type=area&sc_area=AREAM3102&sc_dsp=rs_140956'),index=[21])
df22=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/h083700/?sc_type=area&sc_area=PREF01&sc_dsp=rs_140690'),index=[22])
df23=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/s4nre9kb0000/?sc_type=area&sc_area=jp&sc_dsp=rs_143321'),index=[23])
df24=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/k091300/?sc_type=area&sc_area=AREAL3102&sc_dsp=rs_140923'),index=[24])
df25=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/k447404/?sc_type=area&sc_area=AREAL3102&sc_dsp=rs_141091'),index=[25])

df26=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/f041700/?sc_type=area&sc_area=PREF40&sc_dsp=rs_137047'),index=[26])
df27=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/mn61z9r90000/?sc_type=area&sc_area=PREF01&sc_dsp=rs_140776'),index=[27])

df28=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/bzd40cs80000/?sc_type=area&sc_area=AREAL3102&sc_dsp=rs_141671'),index=[28])
df29=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/h299600/?sc_type=area&sc_area=PREF01&sc_dsp=rs_140719'),index=[29])
df30=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/h132400/?sc_type=area&sc_area=PREF01&sc_dsp=rs_140696'),index=[30])
df31=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/mwmgbcpa0000/?sc_type=area&sc_area=AREAL3102&sc_dsp=rs_142059'),index=[31])
df32=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/b6ch60rw0000/?sc_type=area&sc_area=jp&sc_dsp=rs_139997'),index=[32])
df33=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/r0yajkf80000/?sc_type=area&sc_area=PREF01&sc_dsp=rs_140757'),index=[33])

df34=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/s680fsza0000/?sc_type=area&sc_area=AREAL3102&sc_dsp=rs_141718'),index=[34])
df35=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/1s713pkh0000/?sc_type=area&sc_area=jp&sc_dsp=rs_143586'),index=[35])
df36=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/5jnx16v40000/?sc_type=area&sc_area=PREF01&sc_dsp=rs_140671'),index=[36])
df37=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/k021906/?sc_type=area&sc_area=AREAL3102&sc_dsp=rs_140869'),index=[37])
df38=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/7cwy1ujr0000/?sc_type=area&sc_area=jp&sc_dsp=rs_139086'),index=[38])
df39=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/ee3su7vg0000/?sc_type=area&sc_area=PREF01&sc_dsp=rs_140819'),index=[39])

df40=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/rkv5xwyd0000/?sc_type=area&sc_area=AREAL3102&sc_dsp=rs_141655'),index=[40])
df41=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/fzbkfkzs0000/?sc_type=area&sc_area=jp&sc_dsp=rs_142859'),index=[41])
df42=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/h210301/?sc_type=area&sc_area=PREF01&sc_dsp=rs_140702'),index=[42])

df43=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/f000302/?sc_type=area&sc_area=PREF40&sc_dsp=rs_137010'),index=[43])
df44=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/42vm7f450000/'),index=[44])
df45=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/5jnx16v40000/?sc_type=area&sc_area=PREF01&sc_dsp=rs_140671'),index=[45])
df46=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/f524600/?sc_type=area&sc_area=PREF40&sc_dsp=rs_137195'),index=[46])
df47=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/dyyp9rcg0000/?sc_type=area&sc_area=jp&sc_dsp=rs_140432'),index=[47])
df48=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/906pjp8a0000/?sc_type=area&sc_area=PREF01&sc_dsp=rs_140806'),index=[48])
df49=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/mk32z1g60000/?sc_type=area&sc_area=jp&sc_dsp=rs_140103'),index=[49])
df50=pd.DataFrame(gurunavi('https://r.gnavi.co.jp/cp3ad69f0000/?sc_type=area&sc_area=PREF40&sc_dsp=rs_137125'),index=[50])
#pandas結合
full_data=pd.concat([df01,df02,df03,df04,df05,df06,df07,df08,df09,df10,
          df11,df12,df13,df14,df15,df16,df17,df18,df19,df20,
          df21,df22,df23,df24,df25,df26,df27,df28,df29,df30,
          df31,df32,df33,df34,df35,df36,df37,df38,df39,df40,
          df41,df42,df43,df44,df45,df46,df47,df48,df49,df50])
#csvファイル化
full_data.to_csv('1-1.csv',index=False)

