{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 230,
   "id": "8777aa8d-fca5-4ef1-9728-38c6d1c1420c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'店舗名': '鉄板焼 然荘 ',\n",
       " '電話番号': '050-5485-1247',\n",
       " '都道府県': '兵庫県',\n",
       " '市区町村': '神戸市中央区',\n",
       " '番地': '東川崎町1-3-5',\n",
       " '建物名': '神戸ハーバーランド クラウンパレス神戸',\n",
       " 'URL': 'https://r.gnavi.co.jp/area/jp/rs/?fwp=%E7%A5%9E%E6%88%B8&date=20230411&sc_lid=r-rs_backlink',\n",
       " 'SSL証明書': True}"
      ]
     },
     "execution_count": 230,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "gurunavi('https://r.gnavi.co.jp/kbet302/')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "69c6d21d-be27-4a71-8ceb-602de1e870f1",
   "metadata": {},
   "outputs": [],
   "source": [
    "def ssl(u):\n",
    "        if u.startswith('https://')==True:\n",
    "            return True\n",
    "        else:\n",
    "            return False\n",
    "ss=ssl(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eb4ad772-6dc2-4e6c-89ea-b69c61ca1db6",
   "metadata": {},
   "outputs": [],
   "source": [
    "def ssl(u):\n",
    "        if u.startswith('https://')==True:\n",
    "            return True\n",
    "        else:\n",
    "            return False\n",
    "    ss=ssl(url)\n",
    "    details[\"SSL証明書\"]=ss"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 149,
   "id": "62a3c264-ae80-4ef8-8f31-38a452f68e35",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<selenium.webdriver.chrome.webdriver.WebDriver (session=\"f79aa6d55a7c0732616b52c34721c29b\")>"
      ]
     },
     "execution_count": 149,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a57bf4f4-292a-4d33-b62f-2c1faab8593a",
   "metadata": {},
   "outputs": [],
   "source": [
    "#URL\n",
    "web=soup.find('link')\n",
    "print(web.get('href'))\n",
    "#SSL\n",
    "def ssl(url):\n",
    "    print(url.startswith('https://'))\n",
    "ssl(web.get('href'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 294,
   "id": "33afa801-2cf2-4a7d-a576-5339badf5085",
   "metadata": {},
   "outputs": [],
   "source": [
    "from selenium import webdriver"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 293,
   "id": "2eb01189-9c1d-4a6d-9006-f823c7a79bd8",
   "metadata": {},
   "outputs": [],
   "source": [
    "def gurunavi(url):\n",
    "    details={}\n",
    "    \n",
    "    #店名\n",
    "    shop=browser.find_element(By.CLASS_NAME, \"shop-info__name\").text\n",
    "    details['店舗名']=shop\n",
    "    #電話番号\n",
    "    tel=browser.find_element(By.CLASS_NAME, \"phone-guide__number\").text\n",
    "    details['電話番号']=tel\n",
    "    #住所　市区町村\n",
    "    ad=browser.find_element(By.CLASS_NAME, \"region\").text\n",
    "    import re\n",
    "    def divide_address(address):\n",
    "        matches = re.match(r'(...??[都道府県])((?:旭川|伊達|石狩|盛岡|奥州|田村|南相馬|那須塩原|東村山|武蔵村山|羽村|十日町|上越|富山|野々市|大町|蒲郡|四日市|姫路|大和郡山|廿日市|下松|岩国|田川|大村)市|.+?郡(?:玉村|大町|.+?)[町村]|.+?市.+?区|.+?[市区町村])(.+)' , address)\n",
    "        address=[matches[1],matches[2],matches[3]]\n",
    "        return address\n",
    "    details['都道府県']=divide_address(ad)[0]\n",
    "    details['市区町村']=divide_address(ad)[1]\n",
    "    details['番地']=divide_address(ad)[2]\n",
    "    details['建物名']=browser.find_element(By.CLASS_NAME, \"locality\").text \n",
    "    #URL\n",
    "    elem=browser.find_element(By.CLASS_NAME, \"clickable\")\n",
    "    url=elem.find_element(By.TAG_NAME,'a').get_attribute('href')\n",
    "    details[\"URL\"]=url\n",
    "    #SSL\n",
    "    def ssl(u):\n",
    "        if u.startswith('https://')==True:\n",
    "            return True\n",
    "        else:\n",
    "            return False\n",
    "    ss=ssl(url)\n",
    "    details[\"SSL証明書\"]=ss\n",
    "    return details"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2c73787a-c4c4-4fdb-9fcd-1ac7161237d4",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('札幌')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df0=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 295,
   "id": "e88d7651-3385-478b-8e59-a7048b4eaaea",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('札幌')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df02=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 298,
   "id": "e0265bce-4272-42ed-b923-42ac4124dbdf",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('釧路')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df03=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 301,
   "id": "9e32ec51-7e7f-4ebe-84eb-2e820b6a07c4",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('函館')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 308,
   "id": "7902d647-5ad4-4966-9c25-8f749b1e3bee",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('小樽')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 313,
   "id": "fb8a4386-3b40-45f2-89c1-ec79304d2c70",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('八戸')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df06=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 405,
   "id": "94a8d1f3-67a5-4a2a-95d6-e80b34defd77",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('守口')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df07=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 320,
   "id": "7b022179-95ed-4c93-88d0-b6f2be013b71",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('盛岡')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df08=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 323,
   "id": "a39472f1-c8f7-40a5-9265-c369ca145eae",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('釜石')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df09=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 324,
   "id": "4f4bb751-7243-4de1-aeee-c7c60b165497",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('釜石')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df10=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 327,
   "id": "d7cf15ff-4d17-4e3e-95c2-f186764006af",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('仙台')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df11=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 333,
   "id": "13817e6d-8e78-4d1f-88e8-dedb60175e61",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('長岡')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df12=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 334,
   "id": "f2c9de0d-d81a-40e3-9ade-a5d480233168",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('会津若松')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df13=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 337,
   "id": "9d0b365a-7d2a-4248-b5ab-6c00fe870017",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('高崎')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df14=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 339,
   "id": "cbeedcdc-2467-4546-a2d8-3520a8a2d4d8",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('川越')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df15=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 343,
   "id": "194fea6e-62ad-4604-9d4c-aaa566739dff",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('浜松')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df16=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 344,
   "id": "8dcb495d-0a27-4c2e-a4cd-34156d82925d",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('つくば')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df17=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 345,
   "id": "9e36b433-eb36-421b-ad9f-6349f621b990",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('水戸')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df18=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 346,
   "id": "ddfeeb4e-9249-45c4-a1e8-83bb3f27ab1e",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('土浦')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df19=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 347,
   "id": "6df71a76-a4dc-41e0-a203-e65a50b49c03",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('船橋')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df20=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 348,
   "id": "c0afc18c-b712-4610-9817-fc67d0671ecb",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('成田')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df21=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 349,
   "id": "ae892880-a64a-41fe-8387-c9bb1c430805",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('八王子')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df22=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 351,
   "id": "36a35652-e0f9-49fd-b655-7ab2e2458b02",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('府中')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df23=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 352,
   "id": "ee260ab4-8830-4d97-8c33-d4286ff39d25",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('調布')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df24=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 353,
   "id": "b8b94acb-dfe5-46ca-8b99-47b5161a35f1",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('三鷹')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df25=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 354,
   "id": "cf284949-7b28-414f-9e9f-cd8c53a8b904",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('横浜')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df26=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 356,
   "id": "1bf03a40-4693-4471-82b7-fce973158512",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('鎌倉')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df27=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 357,
   "id": "626ac7fb-bc25-4139-8960-0aee167f30c1",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('川崎')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df28=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 358,
   "id": "338cc2a7-bded-4c9d-9b3f-95386b19c33c",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('厚木')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df29=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 359,
   "id": "da06ed46-cad2-4abf-bf8b-c6beac7852d8",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('小田原')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df30=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 360,
   "id": "2e59c7e1-060f-4d18-b881-d64e6c716fb6",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('甲府')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df31=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 363,
   "id": "4620ffb1-da33-4c79-b1db-f1314fcd09d0",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('姫路')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df32=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 364,
   "id": "df96021c-3b5a-4cfa-a913-0c9b4bf7b7a8",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('名古屋')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df33=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 365,
   "id": "103e534a-cbed-49bd-8c5a-805a4acf5d68",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('金沢')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df34=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 373,
   "id": "df149fbe-6d89-4e85-9fa2-793616a919f1",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('明石')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df35=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 379,
   "id": "1ce5d520-3b91-49c7-81eb-2680583d584c",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('四日市')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df36=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 380,
   "id": "f4f8e97e-68ea-448f-aaea-c629fc928f24",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('和泉')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df37=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 381,
   "id": "138cae55-b5ce-4768-8ee1-1b44082eb00f",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('八尾')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df38=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 382,
   "id": "3e24c0a9-6d04-4e60-8ae1-9773cb495bc6",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('京都')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df39=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 384,
   "id": "757b044a-5f29-4d91-9148-d6e97477f1d2",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('宝塚')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df40=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 385,
   "id": "387e23db-e9e2-409e-9aab-3e8df28744d7",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('広島')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df41=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 388,
   "id": "99203bb0-a4cc-4966-8f2c-fe14ed97871d",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('高槻')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df42=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 390,
   "id": "f308fde5-cc7d-4d1f-a1f0-d84bb41a67f0",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('箕面')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df43=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 393,
   "id": "3a059bbe-3e63-4ccb-826f-d712aac36a1e",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('枚方')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df44=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 394,
   "id": "0e11777c-283e-4c67-8421-8dd3897020d6",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('相模原')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df45=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 395,
   "id": "dcfbec4b-94a7-4a54-87cd-ed7d42be1af1",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('北九州')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df46=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 397,
   "id": "d136810b-c7ca-4ce4-8382-b05d54245324",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('寝屋川')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df47=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 398,
   "id": "d4f22f16-c06a-4f1e-a2d6-3b1d24772e6f",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('佐世保')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df48=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 399,
   "id": "d1ab0361-2ade-46c9-b4bb-ec5ebc887de1",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('熱海')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df49=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 400,
   "id": "98f9e3ba-8d97-4044-ad35-91fde06af9f0",
   "metadata": {},
   "outputs": [],
   "source": [
    "browser=webdriver.Chrome()\n",
    "browser.get('https://www.gnavi.co.jp')\n",
    "from selenium.webdriver.common.by import By\n",
    "elem_area=browser.find_element(By.ID,'js-suggest-area')\n",
    "elem_area.send_keys('下関')\n",
    "from selenium.webdriver.common.by import By\n",
    "search_btn=browser.find_elements(By.CLASS_NAME, \"c-button\")[0]\n",
    "search_btn.click()\n",
    "search_btn=browser.find_element(By.CLASS_NAME, \"style_titleLink__oiHVJ\")\n",
    "url=search_btn.click()\n",
    "df50=gurunavi(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 401,
   "id": "57aa1b1f-ae88-47c2-a107-0c6b51c06baf",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 406,
   "id": "2e7beac6-a608-41d6-9cf8-7331a9ba8366",
   "metadata": {},
   "outputs": [],
   "source": [
    "data01=pd.DataFrame(df01,index=[1])\n",
    "data02=pd.DataFrame(df02,index=[2])\n",
    "data03=pd.DataFrame(df03,index=[3])\n",
    "data04=pd.DataFrame(df04,index=[4])\n",
    "data05=pd.DataFrame(df05,index=[5])\n",
    "data06=pd.DataFrame(df06,index=[6])\n",
    "data07=pd.DataFrame(df07,index=[7])\n",
    "data08=pd.DataFrame(df08,index=[8])\n",
    "data09=pd.DataFrame(df09,index=[9])\n",
    "data10=pd.DataFrame(df10,index=[10])\n",
    "data11=pd.DataFrame(df11,index=[11])\n",
    "data12=pd.DataFrame(df12,index=[12])\n",
    "data13=pd.DataFrame(df13,index=[13])\n",
    "data14=pd.DataFrame(df14,index=[14])\n",
    "data15=pd.DataFrame(df15,index=[15])\n",
    "data16=pd.DataFrame(df16,index=[16])\n",
    "data17=pd.DataFrame(df17,index=[17])\n",
    "data18=pd.DataFrame(df18,index=[18])\n",
    "data19=pd.DataFrame(df19,index=[19])\n",
    "data20=pd.DataFrame(df20,index=[20])\n",
    "data21=pd.DataFrame(df21,index=[21])\n",
    "data22=pd.DataFrame(df22,index=[22])\n",
    "data23=pd.DataFrame(df23,index=[23])\n",
    "data24=pd.DataFrame(df24,index=[24])\n",
    "data25=pd.DataFrame(df25,index=[25])\n",
    "data26=pd.DataFrame(df26,index=[26])\n",
    "data27=pd.DataFrame(df27,index=[27])\n",
    "data28=pd.DataFrame(df28,index=[28])\n",
    "data29=pd.DataFrame(df29,index=[29])\n",
    "data30=pd.DataFrame(df30,index=[30])\n",
    "data31=pd.DataFrame(df31,index=[31])\n",
    "data32=pd.DataFrame(df32,index=[32])\n",
    "data33=pd.DataFrame(df33,index=[33])\n",
    "data34=pd.DataFrame(df34,index=[34])\n",
    "data35=pd.DataFrame(df35,index=[35])\n",
    "data36=pd.DataFrame(df36,index=[36])\n",
    "data37=pd.DataFrame(df37,index=[37])\n",
    "data38=pd.DataFrame(df38,index=[38])\n",
    "data39=pd.DataFrame(df39,index=[39])\n",
    "data40=pd.DataFrame(df40,index=[40])\n",
    "data41=pd.DataFrame(df41,index=[41])\n",
    "data42=pd.DataFrame(df42,index=[42])\n",
    "data43=pd.DataFrame(df43,index=[43])\n",
    "data44=pd.DataFrame(df44,index=[44])\n",
    "data45=pd.DataFrame(df45,index=[45])\n",
    "data46=pd.DataFrame(df46,index=[46])\n",
    "data47=pd.DataFrame(df47,index=[47])\n",
    "data48=pd.DataFrame(df48,index=[48])\n",
    "data49=pd.DataFrame(df49,index=[49])\n",
    "data50=pd.DataFrame(df50,index=[50])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 408,
   "id": "07d7354b-3953-4216-ac42-e837dd135e57",
   "metadata": {},
   "outputs": [],
   "source": [
    "full_data=pd.concat([data01,data02,data03,data04,data05,data06,data07,data08,data09,data10,\n",
    "                    data11,data12,data13,data14,data15,data16,data17,data18,data19,data20,\n",
    "                    data21,data22,data23,data24,data25,data26,data27,data28,data29,data30,\n",
    "                    data31,data32,data33,data34,data35,data36,data37,data38,data39,data40,\n",
    "                    data41,data42,data43,data44,data45,data46,data47,data48,data49,data50])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 409,
   "id": "2c9ea553-e201-4ea0-b309-1ea77f02e240",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>店舗名</th>\n",
       "      <th>電話番号</th>\n",
       "      <th>都道府県</th>\n",
       "      <th>市区町村</th>\n",
       "      <th>番地</th>\n",
       "      <th>建物名</th>\n",
       "      <th>URL</th>\n",
       "      <th>SSL証明書</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>鉄板焼 然荘</td>\n",
       "      <td>050-5485-1247</td>\n",
       "      <td>兵庫県</td>\n",
       "      <td>神戸市中央区</td>\n",
       "      <td>東川崎町1-3-5</td>\n",
       "      <td>神戸ハーバーランド クラウンパレス神戸</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E7%A5%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>しゃぶしゃぶ 十勝晴れ 札幌東急店</td>\n",
       "      <td>050-5488-8648</td>\n",
       "      <td>北海道</td>\n",
       "      <td>札幌市中央区</td>\n",
       "      <td>北4条西2</td>\n",
       "      <td>さっぽろ東急百貨店10F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E6%9C%A...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>パーラー フタバヤ</td>\n",
       "      <td>050-5486-0287</td>\n",
       "      <td>北海道</td>\n",
       "      <td>函館市</td>\n",
       "      <td>美原1-7-1</td>\n",
       "      <td>メガドンキホーテ函館店2F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%87%B...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>パーラー フタバヤ</td>\n",
       "      <td>050-5486-0287</td>\n",
       "      <td>北海道</td>\n",
       "      <td>函館市</td>\n",
       "      <td>美原1-7-1</td>\n",
       "      <td>メガドンキホーテ函館店2F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%87%B...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>小樽ビュッフェレストラン Sizzle</td>\n",
       "      <td>050-5486-7782</td>\n",
       "      <td>北海道</td>\n",
       "      <td>小樽市</td>\n",
       "      <td>色内1-4-16</td>\n",
       "      <td>ホテルノルド小樽2F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%B0%8...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>個室空間 湯葉豆腐料理 福福屋\\n弘前駅前店</td>\n",
       "      <td>0172-36-5288</td>\n",
       "      <td>青森県</td>\n",
       "      <td>弘前市</td>\n",
       "      <td>大字駅前町1-1-1</td>\n",
       "      <td>東横イン弘前駅前ビル1F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%BC%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>焼とり 居酒屋 まるよし</td>\n",
       "      <td>050-5487-6189</td>\n",
       "      <td>大阪府</td>\n",
       "      <td>守口市</td>\n",
       "      <td>京阪本通2-1-5</td>\n",
       "      <td>守口PKIビル1F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%AE%8...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>ビアベース ベアレン 盛岡駅前</td>\n",
       "      <td>050-5492-9812</td>\n",
       "      <td>岩手県</td>\n",
       "      <td>盛岡市</td>\n",
       "      <td>盛岡駅前通8-11</td>\n",
       "      <td>盛岡駅前ビルB1</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E7%9B%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>大戸屋 ごはん処 イオンタウン釜石店</td>\n",
       "      <td>0193-55-5364</td>\n",
       "      <td>岩手県</td>\n",
       "      <td>釜石市</td>\n",
       "      <td>港町2-1-1</td>\n",
       "      <td>イオンタウン釜石2F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E9%87%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>大戸屋 ごはん処 イオンタウン釜石店</td>\n",
       "      <td>0193-55-5364</td>\n",
       "      <td>岩手県</td>\n",
       "      <td>釜石市</td>\n",
       "      <td>港町2-1-1</td>\n",
       "      <td>イオンタウン釜石2F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E9%87%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>利久の和食処 松島</td>\n",
       "      <td>022-226-8729</td>\n",
       "      <td>宮城県</td>\n",
       "      <td>仙台市青葉区</td>\n",
       "      <td>中央1-1-1</td>\n",
       "      <td>エスパル仙台B1</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E4%BB%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>AallaZ（アー・アッラ・ゼータ） 長岡</td>\n",
       "      <td>050-5484-2707</td>\n",
       "      <td>新潟県</td>\n",
       "      <td>長岡市</td>\n",
       "      <td>高畑町660</td>\n",
       "      <td>S．H．S長岡店3F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E9%95%B...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>寧々家 会津若松駅前店</td>\n",
       "      <td>050-5485-9811</td>\n",
       "      <td>福島県</td>\n",
       "      <td>会津若松市</td>\n",
       "      <td>駅前町1-10</td>\n",
       "      <td>会津若松駅食品館ピボット内</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E4%BC%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>高崎個室 和食 やまどり</td>\n",
       "      <td>050-5492-2433</td>\n",
       "      <td>群馬県</td>\n",
       "      <td>高崎市</td>\n",
       "      <td>東町3-5</td>\n",
       "      <td>ホテルココ・グラン高崎1F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E9%AB%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>中華そば 神寄 エキア川越店</td>\n",
       "      <td>050-5484-2313</td>\n",
       "      <td>埼玉県</td>\n",
       "      <td>川越市</td>\n",
       "      <td>脇田町24-9</td>\n",
       "      <td>エキア川越</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%B7%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>海鮮と産地鶏の炭火焼き\\nうお鶏 浜松駅前店</td>\n",
       "      <td>050-5484-2472</td>\n",
       "      <td>静岡県</td>\n",
       "      <td>浜松市中区</td>\n",
       "      <td>鍛冶町140</td>\n",
       "      <td>浜松イズムCビルB1</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E6%B5%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>ワインとピザ ビストロ ポリッツァ</td>\n",
       "      <td>050-5486-5549</td>\n",
       "      <td>茨城県</td>\n",
       "      <td>つくば市</td>\n",
       "      <td>吾妻1-8-10</td>\n",
       "      <td>Biviつくば</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E3%81%A...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>韓国屋台料理と純豆腐のお店 ポチャ 水戸OPA店</td>\n",
       "      <td>050-5485-7431</td>\n",
       "      <td>茨城県</td>\n",
       "      <td>水戸市</td>\n",
       "      <td>宮町1-7-33</td>\n",
       "      <td>水戸サウスタワー</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E6%B0%B...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>食べ飲み放題 大衆食堂 安べゑ\\n土浦駅前店</td>\n",
       "      <td>050-5484-6455</td>\n",
       "      <td>茨城県</td>\n",
       "      <td>土浦市</td>\n",
       "      <td>大和町4-3</td>\n",
       "      <td>ウエストビル土浦</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%9C%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>鳥元 船橋フェイス店</td>\n",
       "      <td>050-5493-6315</td>\n",
       "      <td>千葉県</td>\n",
       "      <td>船橋市</td>\n",
       "      <td>本町1-3-1</td>\n",
       "      <td>船橋フェイスビルB1</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E8%88%B...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>Cafe＆Kitchen\\nDanRan JR成田西口店</td>\n",
       "      <td>050-5485-3231</td>\n",
       "      <td>千葉県</td>\n",
       "      <td>成田市</td>\n",
       "      <td>馬橋8-3</td>\n",
       "      <td>成田駅2F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E6%88%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>千房 セレオ八王子支店</td>\n",
       "      <td>050-5486-8400</td>\n",
       "      <td>東京都</td>\n",
       "      <td>八王子市</td>\n",
       "      <td>旭町1-1</td>\n",
       "      <td>セレオ八王子北館9F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%85%A...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>大戸屋 ごはん処 府中北口店</td>\n",
       "      <td>042-352-2950</td>\n",
       "      <td>東京都</td>\n",
       "      <td>府中市</td>\n",
       "      <td>府中町1-1-5</td>\n",
       "      <td>府中高木ビルB1</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%BA%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>ローカルインディア 調布パルコ店</td>\n",
       "      <td>050-5494-3044</td>\n",
       "      <td>東京都</td>\n",
       "      <td>調布市</td>\n",
       "      <td>小島町1-38-1</td>\n",
       "      <td>調布パルコ</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E8%AA%B...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>鳥元 三鷹コラル店</td>\n",
       "      <td>050-5493-6192</td>\n",
       "      <td>東京都</td>\n",
       "      <td>三鷹市</td>\n",
       "      <td>下連雀3-35-1</td>\n",
       "      <td>三鷹コラル4F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E4%B8%8...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>カステリーナ 横浜</td>\n",
       "      <td>050-5488-2070</td>\n",
       "      <td>神奈川県</td>\n",
       "      <td>横浜市西区</td>\n",
       "      <td>北幸2-6-5</td>\n",
       "      <td>GEMS横浜4F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E6%A8%A...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>濱焼北海道魚萬 鎌倉東口駅前店</td>\n",
       "      <td>0467-60-1088</td>\n",
       "      <td>神奈川県</td>\n",
       "      <td>鎌倉市</td>\n",
       "      <td>小町1-6-17</td>\n",
       "      <td>鎌倉マークビル B1</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E9%8E%8...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>しゃぶ禅 川崎店</td>\n",
       "      <td>044-245-9700</td>\n",
       "      <td>神奈川県</td>\n",
       "      <td>川崎市川崎区</td>\n",
       "      <td>日進町1</td>\n",
       "      <td>川崎日航ホテル5F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%B7%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>茶薫 小籠包 本厚木ミロード店</td>\n",
       "      <td>050-5489-3191</td>\n",
       "      <td>神奈川県</td>\n",
       "      <td>厚木市</td>\n",
       "      <td>泉町1-1</td>\n",
       "      <td>本厚木ミロード7F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%8E%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>小田原 みなと食堂</td>\n",
       "      <td>050-5489-4858</td>\n",
       "      <td>神奈川県</td>\n",
       "      <td>小田原市</td>\n",
       "      <td>栄町1-1-15</td>\n",
       "      <td>ミナカ小田原 小田原新城下町1F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%B0%8...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>31</th>\n",
       "      <td>山内農場 甲府南口駅前店</td>\n",
       "      <td>055-223-9788</td>\n",
       "      <td>山梨県</td>\n",
       "      <td>甲府市</td>\n",
       "      <td>丸の内1-2-9</td>\n",
       "      <td>甲府駅前貸店舗1・2F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E7%94%B...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>千姫茶屋</td>\n",
       "      <td>050-5494-1151</td>\n",
       "      <td>兵庫県</td>\n",
       "      <td>姫路市</td>\n",
       "      <td>本町68-290</td>\n",
       "      <td>イーグレひめじ1F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%A7%A...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>和食・居酒屋 開</td>\n",
       "      <td>050-5485-2927</td>\n",
       "      <td>愛知県</td>\n",
       "      <td>名古屋市中村区</td>\n",
       "      <td>椿町12-21</td>\n",
       "      <td>ナゴヤグランドホテル1F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%90%8...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>和食・割烹 彩旬\\nアパホテル金沢駅前</td>\n",
       "      <td>050-5484-5702</td>\n",
       "      <td>石川県</td>\n",
       "      <td>金沢市</td>\n",
       "      <td>広岡1-9-28</td>\n",
       "      <td>アパホテル金沢駅前</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E9%87%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>道場</td>\n",
       "      <td>050-5484-5337</td>\n",
       "      <td>兵庫県</td>\n",
       "      <td>明石市</td>\n",
       "      <td>大明石町1-1-23</td>\n",
       "      <td>ピオレ明石</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E6%98%8...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>36</th>\n",
       "      <td>サイゼリヤ ララスクエア四日市店</td>\n",
       "      <td>059-350-5055</td>\n",
       "      <td>三重県</td>\n",
       "      <td>四日市市</td>\n",
       "      <td>安島1-3-31</td>\n",
       "      <td>トナリエ四日市5F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%9B%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>37</th>\n",
       "      <td>bibim ららぽーと和泉店</td>\n",
       "      <td>050-5492-1591</td>\n",
       "      <td>大阪府</td>\n",
       "      <td>和泉市</td>\n",
       "      <td>あゆみ野4-4-7</td>\n",
       "      <td>ららぽーと和泉</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%92%8...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>38</th>\n",
       "      <td>鰻のもり</td>\n",
       "      <td>050-5485-0295</td>\n",
       "      <td>大阪府</td>\n",
       "      <td>八尾市</td>\n",
       "      <td>北本町2-1-1</td>\n",
       "      <td>近鉄八尾駅2F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%85%A...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>39</th>\n",
       "      <td>麺ざんまい 近鉄京都駅店</td>\n",
       "      <td>050-5487-9342</td>\n",
       "      <td>京都府</td>\n",
       "      <td>京都市下京区</td>\n",
       "      <td>東塩小路釜殿町31-1</td>\n",
       "      <td>京都駅</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E4%BA%A...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>40</th>\n",
       "      <td>宝塚ホテル 日本料理「彩羽」</td>\n",
       "      <td>050-5489-4755</td>\n",
       "      <td>兵庫県</td>\n",
       "      <td>宝塚市</td>\n",
       "      <td>栄町1-1-33</td>\n",
       "      <td>宝塚ホテル</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%AE%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>41</th>\n",
       "      <td>ブッフェレストラン「ブリッジ」</td>\n",
       "      <td>050-5485-2698</td>\n",
       "      <td>広島県</td>\n",
       "      <td>広島市東区</td>\n",
       "      <td>若草町12-1</td>\n",
       "      <td>シェラトングランドホテル広島6F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%BA%8...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>42</th>\n",
       "      <td>ビッグエコー 高槻中央店</td>\n",
       "      <td>050-5493-5741</td>\n",
       "      <td>大阪府</td>\n",
       "      <td>高槻市</td>\n",
       "      <td>高槻町12-15</td>\n",
       "      <td>高槻センター街ビル</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E9%AB%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>43</th>\n",
       "      <td>焼鳥屋 鳥貴族 箕面店</td>\n",
       "      <td>072-725-8233</td>\n",
       "      <td>大阪府</td>\n",
       "      <td>箕面市</td>\n",
       "      <td>箕面5-1-52</td>\n",
       "      <td>箕面アルコスビル1F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E7%AE%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>44</th>\n",
       "      <td>濱焼北海道魚萬 枚方市北口駅前店</td>\n",
       "      <td>072-861-2088</td>\n",
       "      <td>大阪府</td>\n",
       "      <td>枚方市</td>\n",
       "      <td>岡本町2-22</td>\n",
       "      <td>枚方デパートメントビルB1</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E6%9E%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>45</th>\n",
       "      <td>サイゼリヤ セレオ相模原店</td>\n",
       "      <td>042-704-0821</td>\n",
       "      <td>神奈川県</td>\n",
       "      <td>相模原市中央区</td>\n",
       "      <td>相模原1-1-3</td>\n",
       "      <td>セレオ相模原3F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E7%9B%B...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>46</th>\n",
       "      <td>黒船 小倉本店</td>\n",
       "      <td>050-5485-6604</td>\n",
       "      <td>福岡県</td>\n",
       "      <td>北九州市小倉北区</td>\n",
       "      <td>馬借1-5-25</td>\n",
       "      <td>ホラヤビルB1</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%8C%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>47</th>\n",
       "      <td>古潭ビバモール寝屋川店</td>\n",
       "      <td>050-5493-8301</td>\n",
       "      <td>大阪府</td>\n",
       "      <td>寝屋川市</td>\n",
       "      <td>寝屋南2-22-2</td>\n",
       "      <td>ビバモール寝屋川2F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%AF%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>48</th>\n",
       "      <td>個室居酒屋 海鮮料理 さかなや道場\\n佐世保駅前店</td>\n",
       "      <td>050-5492-1837</td>\n",
       "      <td>長崎県</td>\n",
       "      <td>佐世保市</td>\n",
       "      <td>白南風町1-13</td>\n",
       "      <td>ＪＲ九州佐世保ビル1F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E4%BD%9...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>49</th>\n",
       "      <td>笑笑 熱海駅前店</td>\n",
       "      <td>0557-83-0588</td>\n",
       "      <td>静岡県</td>\n",
       "      <td>熱海市</td>\n",
       "      <td>田原本町8-6</td>\n",
       "      <td>ハローズ熱海ビル2F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E7%86%B...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50</th>\n",
       "      <td>海鮮浜焼きと創作和食 九十九 ‐つくも‐ 下関駅前店</td>\n",
       "      <td>050-5484-9940</td>\n",
       "      <td>山口県</td>\n",
       "      <td>下関市</td>\n",
       "      <td>竹崎町4-4-1</td>\n",
       "      <td>下関開発ビル1F</td>\n",
       "      <td>https://r.gnavi.co.jp/area/jp/rs/?fwp=%E4%B8%8...</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                             店舗名           電話番号  都道府県      市区町村           番地  \\\n",
       "1                        鉄板焼 然荘   050-5485-1247   兵庫県    神戸市中央区    東川崎町1-3-5   \n",
       "2             しゃぶしゃぶ 十勝晴れ 札幌東急店   050-5488-8648   北海道    札幌市中央区        北4条西2   \n",
       "3                     パーラー フタバヤ   050-5486-0287   北海道       函館市      美原1-7-1   \n",
       "4                     パーラー フタバヤ   050-5486-0287   北海道       函館市      美原1-7-1   \n",
       "5            小樽ビュッフェレストラン Sizzle  050-5486-7782   北海道       小樽市     色内1-4-16   \n",
       "6         個室空間 湯葉豆腐料理 福福屋\\n弘前駅前店   0172-36-5288   青森県       弘前市   大字駅前町1-1-1   \n",
       "7                  焼とり 居酒屋 まるよし   050-5487-6189   大阪府       守口市    京阪本通2-1-5   \n",
       "8               ビアベース ベアレン 盛岡駅前   050-5492-9812   岩手県       盛岡市    盛岡駅前通8-11   \n",
       "9             大戸屋 ごはん処 イオンタウン釜石店   0193-55-5364   岩手県       釜石市      港町2-1-1   \n",
       "10            大戸屋 ごはん処 イオンタウン釜石店   0193-55-5364   岩手県       釜石市      港町2-1-1   \n",
       "11                    利久の和食処 松島    022-226-8729   宮城県    仙台市青葉区      中央1-1-1   \n",
       "12         AallaZ（アー・アッラ・ゼータ） 長岡  050-5484-2707   新潟県       長岡市       高畑町660   \n",
       "13                   寧々家 会津若松駅前店  050-5485-9811   福島県     会津若松市      駅前町1-10   \n",
       "14                 高崎個室 和食 やまどり   050-5492-2433   群馬県       高崎市        東町3-5   \n",
       "15               中華そば 神寄 エキア川越店   050-5484-2313   埼玉県       川越市      脇田町24-9   \n",
       "16        海鮮と産地鶏の炭火焼き\\nうお鶏 浜松駅前店  050-5484-2472   静岡県     浜松市中区       鍛冶町140   \n",
       "17             ワインとピザ ビストロ ポリッツァ  050-5486-5549   茨城県      つくば市     吾妻1-8-10   \n",
       "18     韓国屋台料理と純豆腐のお店 ポチャ 水戸OPA店   050-5485-7431   茨城県       水戸市     宮町1-7-33   \n",
       "19        食べ飲み放題 大衆食堂 安べゑ\\n土浦駅前店  050-5484-6455   茨城県       土浦市       大和町4-3   \n",
       "20                    鳥元 船橋フェイス店  050-5493-6315   千葉県       船橋市      本町1-3-1   \n",
       "21  Cafe＆Kitchen\\nDanRan JR成田西口店  050-5485-3231   千葉県       成田市        馬橋8-3   \n",
       "22                   千房 セレオ八王子支店  050-5486-8400   東京都      八王子市        旭町1-1   \n",
       "23                大戸屋 ごはん処 府中北口店   042-352-2950   東京都       府中市     府中町1-1-5   \n",
       "24             ローカルインディア 調布パルコ店   050-5494-3044   東京都       調布市    小島町1-38-1   \n",
       "25                     鳥元 三鷹コラル店  050-5493-6192   東京都       三鷹市    下連雀3-35-1   \n",
       "26                    カステリーナ 横浜   050-5488-2070  神奈川県     横浜市西区      北幸2-6-5   \n",
       "27              濱焼北海道魚萬 鎌倉東口駅前店    0467-60-1088  神奈川県       鎌倉市     小町1-6-17   \n",
       "28                      しゃぶ禅 川崎店   044-245-9700  神奈川県    川崎市川崎区         日進町1   \n",
       "29               茶薫 小籠包 本厚木ミロード店  050-5489-3191  神奈川県       厚木市        泉町1-1   \n",
       "30                    小田原 みなと食堂   050-5489-4858  神奈川県      小田原市     栄町1-1-15   \n",
       "31                  山内農場 甲府南口駅前店   055-223-9788   山梨県       甲府市     丸の内1-2-9   \n",
       "32                         千姫茶屋   050-5494-1151   兵庫県       姫路市     本町68-290   \n",
       "33                     和食・居酒屋 開   050-5485-2927   愛知県   名古屋市中村区      椿町12-21   \n",
       "34           和食・割烹 彩旬\\nアパホテル金沢駅前  050-5484-5702   石川県       金沢市     広岡1-9-28   \n",
       "35                           道場   050-5484-5337   兵庫県       明石市   大明石町1-1-23   \n",
       "36              サイゼリヤ ララスクエア四日市店   059-350-5055   三重県      四日市市     安島1-3-31   \n",
       "37               bibim ららぽーと和泉店   050-5492-1591   大阪府       和泉市    あゆみ野4-4-7   \n",
       "38                         鰻のもり   050-5485-0295   大阪府       八尾市     北本町2-1-1   \n",
       "39                  麺ざんまい 近鉄京都駅店  050-5487-9342   京都府    京都市下京区  東塩小路釜殿町31-1   \n",
       "40               宝塚ホテル 日本料理「彩羽」   050-5489-4755   兵庫県       宝塚市     栄町1-1-33   \n",
       "41              ブッフェレストラン「ブリッジ」   050-5485-2698   広島県     広島市東区      若草町12-1   \n",
       "42                  ビッグエコー 高槻中央店  050-5493-5741   大阪府       高槻市     高槻町12-15   \n",
       "43                   焼鳥屋 鳥貴族 箕面店   072-725-8233   大阪府       箕面市     箕面5-1-52   \n",
       "44             濱焼北海道魚萬 枚方市北口駅前店    072-861-2088   大阪府       枚方市      岡本町2-22   \n",
       "45                 サイゼリヤ セレオ相模原店   042-704-0821  神奈川県   相模原市中央区     相模原1-1-3   \n",
       "46                       黒船 小倉本店  050-5485-6604   福岡県  北九州市小倉北区     馬借1-5-25   \n",
       "47                  古潭ビバモール寝屋川店   050-5493-8301   大阪府      寝屋川市    寝屋南2-22-2   \n",
       "48     個室居酒屋 海鮮料理 さかなや道場\\n佐世保駅前店  050-5492-1837   長崎県      佐世保市     白南風町1-13   \n",
       "49                      笑笑 熱海駅前店   0557-83-0588   静岡県       熱海市      田原本町8-6   \n",
       "50    海鮮浜焼きと創作和食 九十九 ‐つくも‐ 下関駅前店  050-5484-9940   山口県       下関市     竹崎町4-4-1   \n",
       "\n",
       "                    建物名                                                URL  \\\n",
       "1   神戸ハーバーランド クラウンパレス神戸  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E7%A5%9...   \n",
       "2          さっぽろ東急百貨店10F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E6%9C%A...   \n",
       "3         メガドンキホーテ函館店2F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%87%B...   \n",
       "4         メガドンキホーテ函館店2F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%87%B...   \n",
       "5            ホテルノルド小樽2F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%B0%8...   \n",
       "6          東横イン弘前駅前ビル1F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%BC%9...   \n",
       "7             守口PKIビル1F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%AE%8...   \n",
       "8              盛岡駅前ビルB1  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E7%9B%9...   \n",
       "9            イオンタウン釜石2F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E9%87%9...   \n",
       "10           イオンタウン釜石2F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E9%87%9...   \n",
       "11             エスパル仙台B1  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E4%BB%9...   \n",
       "12           S．H．S長岡店3F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E9%95%B...   \n",
       "13        会津若松駅食品館ピボット内  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E4%BC%9...   \n",
       "14        ホテルココ・グラン高崎1F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E9%AB%9...   \n",
       "15                エキア川越  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%B7%9...   \n",
       "16           浜松イズムCビルB1  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E6%B5%9...   \n",
       "17              Biviつくば  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E3%81%A...   \n",
       "18             水戸サウスタワー  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E6%B0%B...   \n",
       "19             ウエストビル土浦  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%9C%9...   \n",
       "20           船橋フェイスビルB1  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E8%88%B...   \n",
       "21                成田駅2F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E6%88%9...   \n",
       "22           セレオ八王子北館9F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%85%A...   \n",
       "23             府中高木ビルB1  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%BA%9...   \n",
       "24                調布パルコ  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E8%AA%B...   \n",
       "25              三鷹コラル4F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E4%B8%8...   \n",
       "26             GEMS横浜4F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E6%A8%A...   \n",
       "27           鎌倉マークビル B1  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E9%8E%8...   \n",
       "28            川崎日航ホテル5F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%B7%9...   \n",
       "29            本厚木ミロード7F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%8E%9...   \n",
       "30     ミナカ小田原 小田原新城下町1F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%B0%8...   \n",
       "31          甲府駅前貸店舗1・2F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E7%94%B...   \n",
       "32            イーグレひめじ1F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%A7%A...   \n",
       "33         ナゴヤグランドホテル1F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%90%8...   \n",
       "34            アパホテル金沢駅前  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E9%87%9...   \n",
       "35                ピオレ明石  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E6%98%8...   \n",
       "36            トナリエ四日市5F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%9B%9...   \n",
       "37              ららぽーと和泉  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%92%8...   \n",
       "38              近鉄八尾駅2F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%85%A...   \n",
       "39                  京都駅  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E4%BA%A...   \n",
       "40                宝塚ホテル  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%AE%9...   \n",
       "41     シェラトングランドホテル広島6F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%BA%8...   \n",
       "42            高槻センター街ビル  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E9%AB%9...   \n",
       "43           箕面アルコスビル1F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E7%AE%9...   \n",
       "44        枚方デパートメントビルB1  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E6%9E%9...   \n",
       "45             セレオ相模原3F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E7%9B%B...   \n",
       "46              ホラヤビルB1  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%8C%9...   \n",
       "47           ビバモール寝屋川2F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E5%AF%9...   \n",
       "48          ＪＲ九州佐世保ビル1F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E4%BD%9...   \n",
       "49           ハローズ熱海ビル2F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E7%86%B...   \n",
       "50             下関開発ビル1F  https://r.gnavi.co.jp/area/jp/rs/?fwp=%E4%B8%8...   \n",
       "\n",
       "    SSL証明書  \n",
       "1     True  \n",
       "2     True  \n",
       "3     True  \n",
       "4     True  \n",
       "5     True  \n",
       "6     True  \n",
       "7     True  \n",
       "8     True  \n",
       "9     True  \n",
       "10    True  \n",
       "11    True  \n",
       "12    True  \n",
       "13    True  \n",
       "14    True  \n",
       "15    True  \n",
       "16    True  \n",
       "17    True  \n",
       "18    True  \n",
       "19    True  \n",
       "20    True  \n",
       "21    True  \n",
       "22    True  \n",
       "23    True  \n",
       "24    True  \n",
       "25    True  \n",
       "26    True  \n",
       "27    True  \n",
       "28    True  \n",
       "29    True  \n",
       "30    True  \n",
       "31    True  \n",
       "32    True  \n",
       "33    True  \n",
       "34    True  \n",
       "35    True  \n",
       "36    True  \n",
       "37    True  \n",
       "38    True  \n",
       "39    True  \n",
       "40    True  \n",
       "41    True  \n",
       "42    True  \n",
       "43    True  \n",
       "44    True  \n",
       "45    True  \n",
       "46    True  \n",
       "47    True  \n",
       "48    True  \n",
       "49    True  \n",
       "50    True  "
      ]
     },
     "execution_count": 409,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "full_data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 411,
   "id": "da97d979-519c-4b1d-b1a2-3ee32b9b186e",
   "metadata": {},
   "outputs": [],
   "source": [
    "full_data.to_csv('1-2.csv',index=False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
